Repository GPTx-global/guru-v2, pull requests merged in 2025-09, with the labels that each got.

#5 feat/add unit test
  oralce/config/config.go
  oralce/subscriber/subscriber_test.go
  oralce/worker/client_test.go
  oralce/worker/pool_test.go
Labels: feature, tests

#4 fix make test and feepolicy improvements
  Makefile
  ante/testutils/testutil.go
  ibc/simapp/README.md
  ibc/simapp/ante.go
  ibc/simapp/app.go
  ibc/simapp/genesis.go
  ibc/simapp/test_helpers.go
  ibc/testing/chain.go
  ibc/testing/coordinator.go
  ibc/testing/testing_app.go
  x/feepolicy/client/cli/cli.go
  x/feepolicy/client/cli/query.go
  x/feepolicy/client/cli/tx.go
  x/feepolicy/keeper/grpc_query.go
  x/feepolicy/keeper/msg_server.go
  x/feepolicy/module_old.go
  x/feepolicy/types/codec.go
  x/feepolicy/types/discount.go
  x/feepolicy/types/events.go
Labels: build, CLI, feature

#7 fix: update MinGasPrice calculation in AfterOracleEnd function
  x/feemarket/keeper/hooks.go
Labels: feature

#8 feat/change output format and time format
  oralce/daemon/daemon.go
Labels: feature
